#--------------------------------
#       General Params
#--------------------------------
seed: [True, 1337]
train: True
model_id: 'early_testing'
demo: True
torch_home: '~/.cache/torch/'

#--------------------------------
#       Training Params
#--------------------------------

batch_size: 1
num_epochs: 20
accelerator: 'gpu' 
gpu_config: [True, [0]]
valid_rate: 1

#--------------------------------
#       All paths
#--------------------------------

paths: &id001
  path_root:
  path_data: 'data/'
  path_train: 'train/'
  path_valid: 'valid/'
  path_model: 'my_models/'
  path_results: 'results/'
  path_checkpoints: 'checkpoints/'
  path_images: 'images/'

#--------------------------------
#       Classifier
#--------------------------------
classifier:
  num_classes: 10
  architecture: 'resnet18'
  learning_rate: 1.e-3
  transfer_learn: False
  freeze_backbone: False

#--------------------------------
#       Datamodule Params
#--------------------------------
which: 'MNIST' #MNIST
n_cpus: 20
resize_row: 720
resize_col: 720
data_split: 'mnist_1000perClass'
Nxp: 1080
Nyp: 1920
# positive is down and right
lateral_shift_x: 0 # up and down
lateral_shift_y: 0 # left and right

wavefront_transform:
  phase_initialization_strategy: 0

# Start of new parameters
planes:
  0: &idpl00
    name: 'plane0'
    center: [0,0,0]
      #size: [8.96e-3, 15.36e-3]
    size: [8960.0,15360.0]
    normal: [0,0,1]
    Nx: 1080
    Ny: 1920
  1: &idpl01
    name: 'plane1'
    center: [0.0,0.0,318000]
    size: [8960.0,15360.0]
      #size: [5543.2e-6,9676.8e-6]
    normal: [0,0,1]
    Nx: 1080
    Ny: 1920
      #2: &idpl02
      #  name: 'plane2'
      #  center: [0,0,434.9e-3]
      #  size: [8.96e-3, 15.36e-3]
      #  normal: [0,0,1]
      #  Nx: 1080
      #  Ny: 1920

modulators:
  0: &idm00
    amplitude_init : 'uniform'
    phase_init : 'random'
    gradients : 'phase_only'
    phase_pattern : None
    amplitude_pattern : None
    kwargs:
      #1: &idm01
      #  amplitude_init : 'uniform'
      #  phase_init : 'custom'
      #  gradients : 'phase_only'
      #  phase_pattern : 'lens'
      #  amplitude_pattern : None
      #  kwargs:
      #    focal_length: 90.e-3
      #    wavelength: 1.55e-6 

propagator: &idprop
  prop_type: 'rsc'
  wavelength: 0.520

diffraction_blocks:
  0:
    input_plane : *idpl00
    output_plane : *idpl01
    modulator_params : *idm00
    propagator_params : *idprop
      #1:
      #  input_plane : *idpl01
      #  output_plane : *idpl02
      #  modulator_params : *idm01
      #  propagator_params : *idprop

don:
  optimizer: 'ADAM'
  learning_rate: 5.e-2
  transfer_learn: False
  load_checkpoint: False
  objective_function: 'mse'

slm0_host: '10.10.80.1'
slm1_host: '10.10.81.1'
