#--------------------------------
#       General Params
#--------------------------------
seed: [True, 1337]
train: True
model: 'sim2real'
torch_home: '~/.cache/torch/'

#--------------------------------
#       Co-op Training Params
#--------------------------------
batch_size: 1
num_epochs: 5
accelerator: 'gpu' 
gpu_config: [True, [0]]
valid_rate: 1
learning_rate: 3.e-1
crop_normalize_flag: 0

#--------------------------------
#       All paths
#--------------------------------
paths: &id001
  path_root:
  path_data: 'data/baseline'
  path_train: 'train/'
  path_valid: 'valid/'
  path_results: 'results/'
  path_checkpoints: 'checkpoints/'
  path_images: 'images/'
  path_logs: 'logs/'
  path_lens_phase: 'lens_phase/'

#--------------------------------
#       DOM params
#--------------------------------
wavelength: &wavelength 520.e-6

planes:
  0: &idpl00
    name: 'input_plane'
    center: [0,0,0]
    size: [8.64, 15.36]
    normal: [0,0,1]
    Nx: &input_x 1080
    Ny: &input_y 1920
  1: &idpl01
    name: 'calibration_plane'
    center: [0,0, 381]
    size: [8.64, 15.36]
    normal: [0,0,1]
    Nx: 1080
    Ny: 1920
  2: &idpl02
    name: 'lens_plane'
    center: [0,0,762]
    size: [8.64, 15.36]
    normal: [0,0,1]
    Nx: 1080
    Ny: 1920
  3: &idpl03
    name: 'output_plane'
    center: [0,0, 1219.2]
    size: [5.4432, 9.6768]
    normal: [0,0,1]
    Nx: 1080
    Ny: 1920

modulators:
  0: &idm00
    gradients : 'none'
    amplitude_init : 'uniform'
    amplitude_value: 1.0
    pinhole_size: 'none'
    phase_init : 'uniform'
    phase_value: 0.0
    focal_length: 'none'
    wavelength: *wavelength 
  1: &idm01
    gradients : 'complex'
    amplitude_init : 'uniform'
    amplitude_value: 1.0
    pinhole_size: 'none'
    phase_init : 'uniform'
    phase_value: 1.0
    focal_length: 'none'
    wavelength: *wavelength 
  2: &idm02
    gradients : 'none'
    amplitude_init : 'uniform'
    amplitude_value : 1.0
    pinhole_size: 0.0
    phase_init : 'lens_phase'
    phase_value : 0.0
    focal_length: 285.75
    wavelength: *wavelength

propagator: &idprop
  wavelength: *wavelength
  fft_type: 'auto'
  prop_type: 'rsc'
  padded : True

diffraction_blocks:
  0:
    input_plane : *idpl00
    output_plane : *idpl01
    modulator_params : *idm00
    propagator_params : *idprop
  1:
    input_plane : *idpl01
    output_plane : *idpl02
    modulator_params : *idm01
    propagator_params : *idprop
  2:
    input_plane : *idpl02
    output_plane : *idpl03
    modulator_params : *idm02
    propagator_params : *idprop

dom_training:
  optimizer: 'ADAM'
  learning_rate: 3.e-1
  transfer_learn: False
  load_checkpoint: False
  objective_function: 'mse'

#--------------------------------
#       Datamodule Params
#--------------------------------
which: 'sim2real' #MNIST, baseline_bench, sim2real, sim2real_flat
train_percent: 0.8
n_cpus: 20
resize_row: 720
resize_col: 720
data_split: 'data_split_00100.pt'
which_data: 'resampled_sample' # Used for baseline_bench, 'sim_output', 'bench_image', 'resampled_sample'
Nxp: *input_x
Nyp: *input_y
  #shift_x: 200
  #shift_y: 0

wavefront_transform:
  phase_initialization_strategy: 0
