apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  namespace: gpn-mizzou-muem
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
    spec:
      automountServiceAccountToken: false
      affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: topology.kubernetes.io/region
                    operator: In
                    values:
                      - us-central
      containers:
        - name: controller-experiment
          image: kovaleskilab/pirnn:v1
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
          imagePullPolicy: Always
          command: ["/bin/bash", "-c"]
          args: ["/develop/code/entrypoint.sh; python3 /develop/code/PIRNN/src/controller.py"]
          resources:
            requests:
              memory: 8Gi
              cpu: 2
            limits:
              memory: 8Gi
              cpu: 2
          ports:
            - containerPort: 10001
          volumeMounts:
            - name: pirnn-data
              mountPath: /develop/data
            - name: pirnn-results
              mountPath: /develop/results
      volumes:
        - name: pirnn-data
          persistentVolumeClaim:
            claimName: pirnn-data
        - name: pirnn-results
          persistentVolumeClaim:
            claimName: pirnn-results

