apiVersion: v1
kind: Pod
metadata:
  name: coop-monitor
  namespace: gpn-mizzou-muem
spec:
  automountServiceAccountToken: false
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: topology.kubernetes.io/region
              operator: In
              values:
                - us-central
  containers:
    - name: coop-monitor
      image: kovaleskilab/coop:v1
      env:
        - name: PYTHONUNBUFFERED
          value: "1"
      imagePullPolicy: Always
      command: ["sleep"]
      args: ["infinity"]
      resources:
        requests:
          memory: 8Gi
          cpu: 2
        limits:
          memory: 8Gi
          cpu: 2
      volumeMounts:
        - name: coop-data
          mountPath: /develop/data
        - name: coop-results
          mountPath: /develop/results
        - name: dshm
          mountPath: /dev/shm
  volumes:
    - name: coop-data
      persistentVolumeClaim:
        claimName: coop-data
    - name: coop-results
      persistentVolumeClaim:
        claimName: coop-results
    - name: dshm
      emptyDir:
        medium: Memory
