apiVersion: apps/v1
kind: Deployment
metadata:
  name: coop-monitor
  namespace: gpn-mizzou-muem
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coop-monitor
  template:
    metadata:
      labels:
        app: coop-monitor
    spec:
      automountServiceAccountToken: false
      affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: topology.kubernetes.io/region
                    operator: In
                    values:
                      - us-central
      containers:
        - name: coop-monitor
          image: kovaleskilab/coop:v1
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
          imagePullPolicy: Always
          command: ["/bin/bash", "-c"]
          args: ["sleep infinity"]
          resources:
            requests:
              memory: 100Gi
              cpu: 20
              nvidia.com/a100: 1
            limits:
              memory: 100Gi
              cpu: 20
              nvidia.com/a100: 1
          volumeMounts:
            - name: coop-data
              mountPath: /develop/data
            - name: coop-results
              mountPath: /develop/results
      volumes:
        - name: coop-data
          persistentVolumeClaim:
            claimName: coop-data
        - name: coop-results
          persistentVolumeClaim:
            claimName: coop-results
