apiVersion: apps/v1
kind: Deployment
metadata:
  name: pirnn
  namespace: gpn-mizzou-muem
spec:
  replicas: 10
  selector:
    matchLabels:
      app: pirnn
  template:
    metadata:
      labels:
        app: pirnn
    spec:
      automountServiceAccountToken: false
      affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: topology.kubernetes.io/region
                    operator: In
                    values:
                      - us-central
      containers:
        - name: pirnn
          image: kovaleskilab/pirnn:v1
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
          imagePullPolicy: Always
          command: ["/bin/bash", "-c"]
          args: ["/develop/code/entrypoint.sh; python /develop/code/PIRNN/src/pirnn.py"]
          resources:
            limits:
              memory: 1Gi
              cpu: 1
                #nvidia.com/gpu: 1
            requests:
              memory: 1Gi
              cpu: 1
                #nvidia.com/gpu: 1
          ports:
            - containerPort: 10001
          volumeMounts:
            - name: pirnn-data
              mountPath: /develop/data
            - name: pirnn-results
              mountPath: /develop/results
      volumes:
      - name: pirnn-data
        persistentVolumeClaim:
            claimName: pirnn-data
      - name: pirnn-results
        persistentVolumeClaim:
            claimName: pirnn-results
  
