apiVersion: batch/v1
kind: Job
metadata:
  name: pirnn-job
spec:
  template:
    spec:
      automountServiceAccountToken: false
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/region
                operator: In
                values:
                - us-central 
      containers:
      - name: pirnn-job
        image: kovaleskilab/pirnn:v1
        ports:
          - containerPort: 8880
        env:
          - name: NCCL_SOCKET_IFNAME
            value: eth0
          - name: NCCL_DEBUG
            value: INFO
        workingDir: /develop/code
        command: ["/bin/bash", "-c"]
        args: ["/develop/code/entrypoint.sh; python /develop/code/PIRNN/train.py --config /develop/code/PIRNN/train_config/config.yaml"]
        volumeMounts:
            - name: pirnn-data
              mountPath: /develop/data
            - name: pirnn-results
              mountPath: /develop/results
        resources:
            limits:
              memory: 100Gi
              cpu: 16
              nvidia.com/gpu: 1
            requests:
              memory: 100Gi
              cpu: 16
              nvidia.com/gpu: 1
      volumes:
      - name: pirnn-data
        persistentVolumeClaim:
            claimName: pirnn-data
      - name: pirnn-results
        persistentVolumeClaim:
            claimName: pirnn-results
      restartPolicy: Never      
  backoffLimit: 1
