---
apiVersion: v1
kind: Service
metadata:
  name: pirnn
  namespace: gpn-mizzou-muem
spec:
  selector:
    app: pirnn
  ports:
    - protocol: TCP
      port: 10001
      targetPort: 10001
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: controller
  namespace: gpn-mizzou-muem
spec:
  selector:
    app: controller
  ports:
    - protocol: TCP
      port: 10001
      targetPort: 10001
  type: ClusterIP


